package com.keanntech.mall.mbg.mapper;

import com.keanntech.mall.mbg.model.SysRoleAdmin;
import com.keanntech.mall.mbg.model.SysRoleAdminExample;
import com.keanntech.mall.mbg.model.SysRoleAdminKey;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface SysRoleAdminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_admin
     *
     * @mbg.generated Wed Jun 24 08:38:58 CST 2020
     */
    long countByExample(SysRoleAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_admin
     *
     * @mbg.generated Wed Jun 24 08:38:58 CST 2020
     */
    int deleteByExample(SysRoleAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_admin
     *
     * @mbg.generated Wed Jun 24 08:38:58 CST 2020
     */
    int deleteByPrimaryKey(SysRoleAdminKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_admin
     *
     * @mbg.generated Wed Jun 24 08:38:58 CST 2020
     */
    int insert(SysRoleAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_admin
     *
     * @mbg.generated Wed Jun 24 08:38:58 CST 2020
     */
    int insertSelective(SysRoleAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_admin
     *
     * @mbg.generated Wed Jun 24 08:38:58 CST 2020
     */
    List<SysRoleAdmin> selectByExample(SysRoleAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_admin
     *
     * @mbg.generated Wed Jun 24 08:38:58 CST 2020
     */
    SysRoleAdmin selectByPrimaryKey(SysRoleAdminKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_admin
     *
     * @mbg.generated Wed Jun 24 08:38:58 CST 2020
     */
    int updateByExampleSelective(@Param("record") SysRoleAdmin record, @Param("example") SysRoleAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_admin
     *
     * @mbg.generated Wed Jun 24 08:38:58 CST 2020
     */
    int updateByExample(@Param("record") SysRoleAdmin record, @Param("example") SysRoleAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_admin
     *
     * @mbg.generated Wed Jun 24 08:38:58 CST 2020
     */
    int updateByPrimaryKeySelective(SysRoleAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_admin
     *
     * @mbg.generated Wed Jun 24 08:38:58 CST 2020
     */
    int updateByPrimaryKey(SysRoleAdmin record);
}
